module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "1-primitive-background-color": "var(--1-primitive-background-color)",
        "1-primitive-black-text-color": "var(--1-primitive-black-text-color)",
        "1-primitive-border": "var(--1-primitive-border)",
        "1-primitive-primary-color": "var(--1-primitive-primary-color)",
        "1-primitive-pur-white": "var(--1-primitive-pur-white)",
        "azure-radiance100": "var(--azure-radiance100)",
        "azure-radiance200": "var(--azure-radiance200)",
        "azure-radiance300": "var(--azure-radiance300)",
        "azure-radiance400": "var(--azure-radiance400)",
        "azure-radiance50": "var(--azure-radiance50)",
        "azure-radiance500": "var(--azure-radiance500)",
        "azure-radiance600": "var(--azure-radiance600)",
        "azure-radiance700": "var(--azure-radiance700)",
        "azure-radiance800": "var(--azure-radiance800)",
        "azure-radiance900": "var(--azure-radiance900)",
        "azure-radiance950": "var(--azure-radiance950)",
        "colors-blue-b100": "var(--colors-blue-b100)",
        "colors-blue-b200": "var(--colors-blue-b200)",
        "colors-blue-b400": "var(--colors-blue-b400)",
        "colors-blue-b50": "var(--colors-blue-b50)",
        "colors-blue-b500": "var(--colors-blue-b500)",
        "colors-error-error-1": "var(--colors-error-error-1)",
        "colors-error-error-2": "var(--colors-error-error-2)",
        "colors-neutral-g100": "var(--colors-neutral-g100)",
        "colors-neutral-g200": "var(--colors-neutral-g200)",
        "colors-neutral-g50": "var(--colors-neutral-g50)",
        "colors-neutral-g60": "var(--colors-neutral-g60)",
        "colors-neutral-g75": "var(--colors-neutral-g75)",
        "colors-sucess-sucess-1": "var(--colors-sucess-sucess-1)",
        "colors-sucess-sucess-2": "var(--colors-sucess-sucess-2)",
        "colors-warning-warning-1": "var(--colors-warning-warning-1)",
        "colors-warning-warning-2": "var(--colors-warning-warning-2)",
        "lemon-100": "var(--lemon-100)",
        "lemon-200": "var(--lemon-200)",
        "lemon-300": "var(--lemon-300)",
        "lemon-400": "var(--lemon-400)",
        "lemon-50": "var(--lemon-50)",
        "lemon-500": "var(--lemon-500)",
        "lemon-600": "var(--lemon-600)",
        "lemon-700": "var(--lemon-700)",
        "lemon-800": "var(--lemon-800)",
        "lemon-900": "var(--lemon-900)",
        "lemon-950": "var(--lemon-950)",
        "yellow-100": "var(--yellow-100)",
        "yellow-200": "var(--yellow-200)",
        "yellow-300": "var(--yellow-300)",
        "yellow-400": "var(--yellow-400)",
        "yellow-50": "var(--yellow-50)",
        "yellow-500": "var(--yellow-500)",
        "yellow-600": "var(--yellow-600)",
        "yellow-700": "var(--yellow-700)",
        "yellow-800": "var(--yellow-800)",
        "yellow-900": "var(--yellow-900)",
        "yellow-950": "var(--yellow-950)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: [
          "Montserrat",
          "Helvetica",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
