import { ProjectData } from './types';
import { API_BASE_URL } from '../Work/constants';

const commonRelatedProjects = [
  {
    image: `${API_BASE_URL}/uploads/Thumbnail_Akamai_e98ec23a74.webp`,
    title: "Akamai",
    description: "Fusing personality and authenticity",
  },
  {
    image: `${API_BASE_URL}/uploads/BSF_Banner_8bb1b6c31e.webp`,
    title: "BSF",
    description: "Reasserting leadership and expertise",
  },
  {
    image: `${API_BASE_URL}/uploads/DRL_Thumbnail_8bd6627090.webp`,
    title: "DRL Report",
    description: "Treasuring story and symbolism",
  },
  {
    image: `${API_BASE_URL}/uploads/KDEM_thumbanail_f37f8768a9.webp`,
    title: "KDEM Project",
    description: "Revitalizing energy with design",
  },
];

export const projectsData: Record<string, ProjectData> = {
  akamai: {
    id: 'akamai',
    title: 'Akamai',
    bannerImage: `${API_BASE_URL}/uploads/Akamai_Banner_37385fa3d4.webp`,
    question: 'How do we create a digital experience that reflects Akamai\'s leadership in technology?',
    description: 'Akamai is a global leader in content delivery network services, cybersecurity, and cloud service solutions. Our challenge was to create a digital presence that showcases their technological prowess while maintaining accessibility and user engagement.',
    mainImage: `${API_BASE_URL}/uploads/Akamai_Main_37385fa3d4.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'akamai-theme',
  },
  bsf: {
    id: 'bsf',
    title: 'BSF',
    bannerImage: `${API_BASE_URL}/uploads/Banner_BSF_ac3901fcba.webp`,
    question: 'How do we democratise skincare and give everyone the building blocks to better skin?',
    description: 'The passion project of FutureLabs Founder Marc Elrick, BYOMA was pushing for a total skincare reset as the world\'s first brand dedicated to regenerating the skin\'s structure and barrier function – the biggest breakthrough in skin science in the last 10 years.',
    mainImage: `${API_BASE_URL}/uploads/Middle_BSF_d1f41eed46.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'bsf-theme',
  },
  booket: {
    id: 'booket',
    title: 'Booket',
    bannerImage: `${API_BASE_URL}/uploads/Booket_Banner.webp`,
    question: 'How do we revolutionize the way people discover and share books?',
    description: 'Booket is a social platform for book lovers, designed to make reading more engaging and interactive. Our goal was to create an intuitive interface that encourages literary exploration and community building.',
    mainImage: `${API_BASE_URL}/uploads/Booket_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'booket-theme',
  },
  canara: {
    id: 'canara',
    title: 'Canara',
    bannerImage: `${API_BASE_URL}/uploads/Canara_Banner.webp`,
    question: 'How do we transform traditional banking into a modern digital experience?',
    description: 'Canara Bank needed a digital transformation that would maintain their trusted legacy while providing modern banking convenience. We created a seamless digital platform that bridges traditional banking with contemporary user expectations.',
    mainImage: `${API_BASE_URL}/uploads/Canara_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'canara-theme',
  },
  decathlon: {
    id: 'decathlon',
    title: 'Decathlon',
    bannerImage: `${API_BASE_URL}/uploads/Decathlon_Banner.webp`,
    question: 'How do we make sports accessible to everyone through digital innovation?',
    description: 'Decathlon\'s mission is to make sports accessible to all. We helped create a digital platform that simplifies the sports equipment shopping experience while inspiring people to be more active.',
    mainImage: `${API_BASE_URL}/uploads/Decathlon_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'decathlon-theme',
  },
  drlreport: {
    id: 'drlreport',
    title: 'DRL Report',
    bannerImage: `${API_BASE_URL}/uploads/DRL_Banner.webp`,
    question: 'How do we present complex pharmaceutical data in an engaging and accessible way?',
    description: 'Dr. Reddy\'s Laboratories needed a way to present their annual report that would engage stakeholders while maintaining transparency and professionalism. We created an interactive digital report that makes complex data accessible and engaging.',
    mainImage: `${API_BASE_URL}/uploads/DRL_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'drlreport-theme',
  },
  genes: {
    id: 'genes',
    title: 'Genes',
    bannerImage: `${API_BASE_URL}/uploads/banner_beee63dcbf.webp`,
    question: 'How do we make 60 million daily interactions instantly playful and special?',
    description: 'Genes is a revolutionary platform that transforms everyday genetic research into an engaging and intuitive experience. We created a design system that makes complex scientific data accessible while maintaining scientific accuracy.',
    mainImage: `${API_BASE_URL}/uploads/genes_main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'genes-theme',
  },
  kachumbar: {
    id: 'kachumbar',
    title: 'Kachumbar',
    bannerImage: `${API_BASE_URL}/uploads/Kachumbar_Banner.webp`,
    question: 'How do we bring the vibrant flavors of Indian street food to the digital world?',
    description: 'Kachumbar is a modern Indian street food brand that needed a digital presence as fresh and exciting as their cuisine. We created a website that captures the energy and color of Indian street food culture.',
    mainImage: `${API_BASE_URL}/uploads/Kachumbar_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'kachumbar-theme',
  },
  karnataka: {
    id: 'karnataka',
    title: 'Karnataka',
    bannerImage: `${API_BASE_URL}/uploads/Karnataka_Banner.webp`,
    question: 'How do we showcase the rich heritage and modern progress of Karnataka?',
    description: 'The Karnataka government needed a digital platform that would highlight both the state\'s cultural heritage and its position as a technology hub. We created an immersive experience that bridges tradition and innovation.',
    mainImage: `${API_BASE_URL}/uploads/Karnataka_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'karnataka-theme',
  },
  kdem: {
    id: 'kdem',
    title: 'KDEM',
    bannerImage: `${API_BASE_URL}/uploads/KDEM_Banner.webp`,
    question: 'How do we position Karnataka as a global digital economy leader?',
    description: 'The Karnataka Digital Economy Mission needed a platform to showcase the state\'s technological capabilities and attract global investment. We created a dynamic website that highlights Karnataka\'s digital infrastructure and opportunities.',
    mainImage: `${API_BASE_URL}/uploads/KDEM_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'kdem-theme',
  },
  kheemasutra: {
    id: 'kheemasutra',
    title: 'Kheemasutra',
    bannerImage: `${API_BASE_URL}/uploads/bannerimage_83fcc23f64.webp`,
    question: 'How do we seize the sun and create a bright new future?',
    description: 'The first suncare brand launched in the US and still America\'s most trusted, Beiersdorf\'s iconic sunscreen, Coppertone, was blending into an evolving suncare category bursting with both SPF numbers and emerging \'beauty sun\' brands.',
    mainImage: `${API_BASE_URL}/uploads/MIDDLE_IMAGE_6_5c4fa4c082.webp`,
    additionalImages: [
      `${API_BASE_URL}/uploads/middle_image2_672c7d0729.webp`,
      `${API_BASE_URL}/uploads/middle_image_3_c6b3495b0c.webp`,
      `${API_BASE_URL}/uploads/LAYOUT_IMAGE_2_f59c0e1ca7.webp`,
      `${API_BASE_URL}/uploads/layout_image3_8a9657ede2.webp`,
    ],
    relatedProjects: commonRelatedProjects,
    customCSS: 'kheemasutra-theme',
  },
  kosi: {
    id: 'kosi',
    title: 'Kosi',
    bannerImage: `${API_BASE_URL}/uploads/Kosi_Banner.webp`,
    question: 'How do we bring the spirit of adventure to everyday life?',
    description: 'Kosi is an outdoor lifestyle brand that needed to connect with both serious adventurers and casual outdoor enthusiasts. We created a digital experience that inspires exploration while making outdoor gear accessible to all.',
    mainImage: `${API_BASE_URL}/uploads/Kosi_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'kosi-theme',
  },
  kyoorius: {
    id: 'kyoorius',
    title: 'Kyoorius',
    bannerImage: `${API_BASE_URL}/uploads/Kyoorius_Banner.webp`,
    question: 'How do we celebrate creativity in the digital age?',
    description: 'Kyoorius, India\'s premier creative awards platform, needed a digital presence that would showcase the best in design and advertising. We created an immersive platform that celebrates creative excellence and inspires the next generation.',
    mainImage: `${API_BASE_URL}/uploads/Kyoorius_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'kyoorius-theme',
  },
  lam: {
    id: 'lam',
    title: 'LAM',
    bannerImage: `${API_BASE_URL}/uploads/LAM_Banner.webp`,
    question: 'How do we bring semiconductor manufacturing to life through design?',
    description: 'LAM Research, a global leader in semiconductor manufacturing equipment, needed a digital presence that would communicate their complex technology in an accessible way. We created an engaging platform that simplifies complex concepts while maintaining technical accuracy.',
    mainImage: `${API_BASE_URL}/uploads/LAM_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'lam-theme',
    videoUrl: 'https://player.vimeo.com/video/752407847?h=13b15bdad0&badge=0&autopause=0&player_id=0&app_id=58479',
  },
  lendersmark: {
    id: 'lendersmark',
    title: 'LendersMark',
    bannerImage: `${API_BASE_URL}/uploads/LendersMark_Banner.webp`,
    question: 'How do we revolutionize the lending industry through digital innovation?',
    description: 'LendersMark is transforming the lending industry with innovative digital solutions. We created a platform that streamlines the lending process while maintaining security and compliance.',
    mainImage: `${API_BASE_URL}/uploads/LendersMark_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'lendersmark-theme',
  },
  levis: {
    id: 'levis',
    title: 'Levis',
    bannerImage: `${API_BASE_URL}/uploads/Levis_Banner.webp`,
    question: 'How do we bring an iconic denim brand into the digital age?',
    description: 'Levi\'s, the legendary denim brand, needed a digital presence that would connect with modern consumers while honoring their heritage. We created an immersive platform that celebrates their legacy while embracing contemporary digital experiences.',
    mainImage: `${API_BASE_URL}/uploads/Levis_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'levis-theme',
  },
  levisxappeal: {
    id: 'levisxappeal',
    title: 'Levis x Appeal',
    bannerImage: `${API_BASE_URL}/uploads/LevisxAppeal_Banner.webp`,
    question: 'How do we create a unique collaboration that speaks to both brands?',
    description: 'The collaboration between Levi\'s and Appeal needed a digital platform that would showcase their unique partnership. We created an experience that blends both brands\' aesthetics while highlighting their collaborative products.',
    mainImage: `${API_BASE_URL}/uploads/LevisxAppeal_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'levisxappeal-theme',
  },
  mtr: {
    id: 'mtr',
    title: 'MTR',
    bannerImage: `${API_BASE_URL}/uploads/MTR_Banner.webp`,
    question: 'How do we bring traditional Indian cuisine to the digital world?',
    description: 'MTR Foods, a beloved Indian food brand, needed a digital presence that would connect with modern consumers while celebrating their traditional recipes. We created a platform that makes authentic Indian cuisine accessible to a global audience.',
    mainImage: `${API_BASE_URL}/uploads/MTR_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'mtr-theme',
  },
  munchatantra: {
    id: 'munchatantra',
    title: 'Munchatantra',
    bannerImage: `${API_BASE_URL}/uploads/Munchatantra_Banner.webp`,
    question: 'How do we create a digital storytelling platform for Indian mythology?',
    description: 'Munchatantra aims to make Indian mythology accessible to modern audiences through digital storytelling. We created an engaging platform that brings ancient stories to life through contemporary design and interactive elements.',
    mainImage: `${API_BASE_URL}/uploads/Munchatantra_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'munchatantra-theme',
  },
  nandoos: {
    id: 'nandoos',
    title: 'Nandoos',
    bannerImage: `${API_BASE_URL}/uploads/Banner_Nandoos_da81defbec.webp`,
    question: 'How do we change the way the world drinks?',
    description: 'In a drinks market saturated by sugary soft drinks but with a growing global movement towards health and abstinence, Seedlip founder, Ben Branson, saw an opportunity to combine his farming heritage and love of nature and design. Ben\'s early days of experimental distillation in his kitchen at home sparked a cultural shift – as the world\'s first sophisticated, distilled, non-alcoholic spirit was born.',
    mainImage: `${API_BASE_URL}/uploads/Middle_1_f49276e343.webp`,
    additionalImages: [
      `${API_BASE_URL}/uploads/Left_1_9b1032672c.webp`,
      `${API_BASE_URL}/uploads/Right_1_b6a2482285.webp`,
      `${API_BASE_URL}/uploads/Middle_2_daba43142a.webp`,
      `${API_BASE_URL}/uploads/Middle_3_e811ba71fd.webp`,
    ],
    relatedProjects: commonRelatedProjects,
    customCSS: 'nandoos-theme',
  },
  nauvata: {
    id: 'nauvata',
    title: 'Nauvata',
    bannerImage: `${API_BASE_URL}/uploads/Nauvata_Banner.webp`,
    question: 'How do we bring wellness technology to everyday life?',
    description: 'Nauvata is revolutionizing the wellness industry with innovative technology solutions. We created a digital platform that makes wellness tracking and management intuitive and accessible to everyone.',
    mainImage: `${API_BASE_URL}/uploads/Nauvata_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'nauvata-theme',
  },
  pepsico: {
    id: 'pepsico',
    title: 'Pepsico',
    bannerImage: `${API_BASE_URL}/uploads/Pepsico_Banner.webp`,
    question: 'How do we refresh a global beverage brand for the digital age?',
    description: 'PepsiCo needed a digital transformation that would connect with modern consumers while maintaining their iconic brand identity. We created an immersive digital experience that celebrates their heritage while embracing contemporary design trends.',
    mainImage: `${API_BASE_URL}/uploads/Pepsico_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'pepsico-theme',
  },
  pepsicokosi: {
    id: 'pepsicokosi',
    title: 'Pepsico Kosi',
    bannerImage: `${API_BASE_URL}/uploads/PepsicoKosi_Banner.webp`,
    question: 'How do we create a unique collaboration between two iconic brands?',
    description: 'The collaboration between PepsiCo and Kosi needed a digital platform that would showcase their innovative partnership. We created an experience that combines both brands\' strengths while highlighting their collaborative initiatives.',
    mainImage: `${API_BASE_URL}/uploads/PepsicoKosi_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'pepsicokosi-theme',
  },
  practo: {
    id: 'practo',
    title: 'Practo',
    bannerImage: `${API_BASE_URL}/uploads/Practo_Banner.webp`,
    question: 'How do we make healthcare accessible in the digital age?',
    description: 'Practo is transforming healthcare access through digital innovation. We created a user-friendly platform that connects patients with healthcare providers while ensuring security and privacy.',
    mainImage: `${API_BASE_URL}/uploads/Practo_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'practo-theme',
  },
  quaker: {
    id: 'quaker',
    title: 'Quaker',
    bannerImage: `${API_BASE_URL}/uploads/Quaker_Banner.webp`,
    question: 'How do we make healthy breakfast exciting for modern consumers?',
    description: 'Quaker needed to connect with health-conscious modern consumers while maintaining their trusted brand identity. We created a digital experience that makes healthy breakfast options appealing and accessible.',
    mainImage: `${API_BASE_URL}/uploads/Quaker_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'quaker-theme',
  },
  revolutionari: {
    id: 'revolutionari',
    title: 'Revolutionari',
    bannerImage: `${API_BASE_URL}/uploads/Revolutionari_Banner.webp`,
    question: 'How do we revolutionize digital innovation?',
    description: 'Revolutionari is at the forefront of digital transformation, pushing boundaries and creating new possibilities. We created a platform that showcases their innovative approach while making complex technology accessible.',
    mainImage: `${API_BASE_URL}/uploads/Revolutionari_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'revolutionari-theme',
  },
  revolutionariawards: {
    id: 'revolutionariawards',
    title: 'Revolutionari Awards',
    bannerImage: `${API_BASE_URL}/uploads/RevolutionariAwards_Banner.webp`,
    question: 'How do we celebrate digital excellence?',
    description: 'The Revolutionari Awards recognize outstanding achievements in digital innovation. We created a dynamic platform that showcases award winners and inspires future innovators.',
    mainImage: `${API_BASE_URL}/uploads/RevolutionariAwards_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'revolutionariawards-theme',
  },
  sap: {
    id: 'sap',
    title: 'SAP',
    bannerImage: `${API_BASE_URL}/uploads/SAP_Banner.webp`,
    question: 'How do we make enterprise software more human?',
    description: 'SAP needed to make their enterprise solutions more accessible and user-friendly. We created an intuitive interface that simplifies complex business processes while maintaining robust functionality.',
    mainImage: `${API_BASE_URL}/uploads/SAP_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'sap-theme',
  },
  sapgca: {
    id: 'sapgca',
    title: 'SAP GCA',
    bannerImage: `${API_BASE_URL}/uploads/SAPGCA_Banner.webp`,
    question: 'How do we showcase global customer achievements?',
    description: 'SAP\'s Global Customer Awards needed a platform to celebrate customer success stories. We created an engaging experience that highlights innovative uses of SAP technology across industries.',
    mainImage: `${API_BASE_URL}/uploads/SAPGCA_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'sapgca-theme',
  },
  seafund: {
    id: 'seafund',
    title: 'Seafund',
    bannerImage: `${API_BASE_URL}/uploads/Seafund_Banner.webp`,
    question: 'How do we make investment in ocean conservation engaging?',
    description: 'Seafund is dedicated to ocean conservation through innovative investment strategies. We created a platform that makes ocean conservation investment accessible and compelling to potential investors.',
    mainImage: `${API_BASE_URL}/uploads/Seafund_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'seafund-theme',
  },
  shoppersstop: {
    id: 'shoppersstop',
    title: 'Shoppers Stop',
    bannerImage: `${API_BASE_URL}/uploads/ShoppersStop_Banner.webp`,
    question: 'How do we transform retail for the digital age?',
    description: 'Shoppers Stop needed to evolve their retail experience for digital-first consumers. We created an omnichannel platform that bridges physical and digital shopping experiences.',
    mainImage: `${API_BASE_URL}/uploads/ShoppersStop_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'shoppersstop-theme',
  },
  skf: {
    id: 'skf',
    title: 'SKF',
    bannerImage: `${API_BASE_URL}/uploads/SKF_Banner.webp`,
    question: 'How do we make industrial technology accessible?',
    description: 'SKF needed to communicate their complex industrial solutions in an accessible way. We created a digital platform that simplifies technical information while maintaining professional credibility.',
    mainImage: `${API_BASE_URL}/uploads/SKF_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'skf-theme',
  },
  sn: {
    id: 'sn',
    title: 'SN',
    bannerImage: `${API_BASE_URL}/uploads/SN_Banner.webp`,
    question: 'How do we bring social networking to niche communities?',
    description: 'SN is creating specialized social networks for unique communities. We developed a flexible platform that can be customized for different community needs while maintaining a consistent user experience.',
    mainImage: `${API_BASE_URL}/uploads/SN_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'sn-theme',
  },
  swiggy: {
    id: 'swiggy',
    title: 'Swiggy',
    bannerImage: `${API_BASE_URL}/uploads/Swiggy_Banner.webp`,
    question: 'How do we make food delivery more convenient and efficient?',
    description: 'Swiggy is revolutionizing food delivery with innovative technology solutions. We created a platform that makes food delivery more convenient and efficient while maintaining a consistent user experience.',
    mainImage: `${API_BASE_URL}/uploads/Swiggy_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'swiggy-theme',
  },
  terralite: {
    id: 'terralite',
    title: 'Terralite',
    bannerImage: `${API_BASE_URL}/uploads/Terralite_Banner.webp`,
    question: 'How do we make investment in ocean conservation engaging?',
    description: 'Terralite is dedicated to ocean conservation through innovative investment strategies. We created a platform that makes ocean conservation investment accessible and compelling to potential investors.',
    mainImage: `${API_BASE_URL}/uploads/Terralite_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'terralite-theme',
  },
  vbl: {
    id: 'vbl',
    title: 'VBL',
    bannerImage: `${API_BASE_URL}/uploads/VBL_Banner.webp`,
    question: 'How do we make investment in ocean conservation engaging?',
    description: 'VBL is dedicated to ocean conservation through innovative investment strategies. We created a platform that makes ocean conservation investment accessible and compelling to potential investors.',
    mainImage: `${API_BASE_URL}/uploads/VBL_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'vbl-theme',
  },
  veevilleexperiences: {
    id: 'veevilleexperiences',
    title: 'Veeville Experiences',
    bannerImage: `${API_BASE_URL}/uploads/VeevilleExperiences_Banner.webp`,
    question: 'How do we make investment in ocean conservation engaging?',
    description: 'Veeville Experiences is dedicated to ocean conservation through innovative investment strategies. We created a platform that makes ocean conservation investment accessible and compelling to potential investors.',
    mainImage: `${API_BASE_URL}/uploads/VeevilleExperiences_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'veevilleexperiences-theme',
  },    
  vmware: {
    id: 'vmware',
    title: 'VMware',
    bannerImage: `${API_BASE_URL}/uploads/VMware_Banner.webp`,
    question: 'How do we make investment in ocean conservation engaging?',      
    description: 'VMware is dedicated to ocean conservation through innovative investment strategies. We created a platform that makes ocean conservation investment accessible and compelling to potential investors.',
    mainImage: `${API_BASE_URL}/uploads/VMware_Main.webp`,
    relatedProjects: commonRelatedProjects,
    customCSS: 'vmware-theme',
  },
};
export const getProjectData = (projectId: string): ProjectData | undefined => {
  return projectsData[projectId.toLowerCase()];
}; 