import { 
  Slide, 
  TabItem, 
  Project, 
  CarouselProject, 
  SocialLink, 
  RelatedProject, 
  PortfolioItem,
  SectionBlock 
} from './types';
import { API_BASE_URL } from './constants';

export const slides: Slide[] = [
  {
    image: `${API_BASE_URL}/uploads/Top_Banner_c502c259dd.webp`,
    alt: 'Design Slide 1',
  },
  {
    image: `${API_BASE_URL}/uploads/Top_Banner_b6a01a6873.webp`,
    alt: 'Design Slide 2',
  },
  {
    image: `${API_BASE_URL}/uploads/banner_image_30e24d56c0.webp`,
    alt: 'Design Slide 3',
  },
  {
    image: `${API_BASE_URL}/uploads/RE_Awards_Banner_d1871f8d5a.webp`,
    alt: 'Design Slide 4',
  },
  {
    image: `${API_BASE_URL}/uploads/DRL_Banner_a318e590cf.webp`,
    alt: 'Design Slide 5',
  },
];

export const tabs: TabItem[] = [
  { id: 'All-projects', label: 'All Projects' },
  { id: 'Brand-identity', label: 'Brand Identity' },
  { id: 'Environmental-graphic', label: 'Environment Graphics' },
  { id: 'Book-design', label: 'Book Design' },
  { id: 'Event-design', label: 'Event Design' },
  { id: 'Campaigns', label: 'Campaigns' },
  { id: 'Film-Motion-Graphics', label: 'Film & Motion Graphics' },
  { id: 'Product', label: 'Product' },
];

export const portfolioItems: PortfolioItem[] = [
  {
    id: 'quaker',
    title: 'Quaker - Bowl of growth',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_01_d8cfbaf4fa.webp`,
    link: '/projects/quaker',
  },
  {
    id: 'booket',
    title: 'Booket',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_02_fa51d2f7b6.webp`,
    link: '/projects/booket',
  },
  {
    id: 'kdem',
    title: 'KDEM',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_03_3009241765.webp`,
    link: '/projects/kdem',
  },
  {
    id: 'levis',
    title: 'Levi\'s X Appeal',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_04_17aa32288c.webp`,
    link: '/projects/levis',
  },
  {
    id: 'lendersmark',
    title: 'Lendersmark',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_05_95128ccf07.webp`,
    link: '/projects/lendersmark',
  },
  {
    id: 'vmware',
    title: 'VMware',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/VM_WARE_688b2e8047.webp`,
    link: '/projects/vmware',
  },
  {
    id: 'sapgca',
    title: 'SAP GCA',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_07_98455b3c77.webp`,
    link: '/projects/sapgca',
  },
  {
    id: 'nauvata',
    title: 'Nauvata',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/NAUVATA_67c5d4ab6a.webp`,
    link: '/projects/nauvata',
  },
  {
    id: 'bsf',
    title: 'BSF',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_09_1f75910d6b.webp`,
    link: '/projects/bsf',
  },
  {
    id: 'karnataka',
    title: 'Karnataka',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_10_ec61f835b7.webp`,
    link: '/projects/karnataka',
  },
  {
    id: 'kosi',
    title: 'Kosi',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_11_75c2791aa1.webp`,
    link: '/projects/kosi',
  },
  {
    id: 'revolutionari',
    title: 'Revolutionari',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_12_aae9c075f7.webp`,
    link: '/projects/revolutionari',
  },
  {
    id: 'pepsico',
    title: 'PepsiCo Assam',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_d56114a080.webp`,
    link: '/projects/pepsico',
  },
  {
    id: 'kyoorius',
    title: 'Kyoorius',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_14_a5dc463609.webp`,
    link: '/projects/kyoorius',
  },
  {
    id: 'nandoos',
    title: 'Nandoos',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_15_8ccd7d4d1c.webp`,
    link: '/projects/nandoos',
  },
  {
    id: 'drlreport',
    title: 'DRL Report',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_16_4bf405e26d.webp`,
    link: '/projects/drlreport',
  },
  {
    id: 'sncures',
    title: 'SN Cures',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_17_8e0bc33b3b.webp`,
    link: '/projects/sn',
  },
  {
    id: 'seafund',
    title: 'Seafund',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_f961116ecc.webp`,
    link: '/projects/seafund',
  },
  {
    id: 'mtr',
    title: 'Mera Terah Run',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_19_27687419fe.webp`,
    link: '/projects/mtr',
  },
  {
    id: 'akamai',
    title: 'Akamai',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_20_2425bb02bb.webp`,
    link: '/projects/akamai',
  },
  {
    id: 'munchatantra',
    title: 'Munchatantra',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_21_06531b12d4.webp`,
    link: '/projects/munchatantra',
  },
  {
    id: 'practo',
    title: 'Practo',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/1_22_63db44728c.webp`,
    link: '/projects/practo',
  },
  {
    id: 'fmr',
    title: 'FMR',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/FMR_thumbnail_d2c0a7d11c.webp`,
    link: '/projects/fmr',
  },
  {
    id: 'kachumbar',
    title: 'Kachumbar',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/Thumbnail_kachumbar_a0b71a5e4f.webp`,
    link: '/projects/kachumbar',
  },
  {
    id: 'kheemasutra',
    title: 'Kheemasutra',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/kheemasutra_thumbnail_97210a02b8.webp`,
    link: '/projects/kheemasutra',
  },
  {
    id: 'decathalon',
    title: 'Decathalon',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_4d89d5778d.webp`,
    link: '/projects/decathalon',
  },
  {
    id: 'dilsenaman',
    title: 'Dil Se naman',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_2d5138c5d9.webp`,
    link: '/projects/dilsenaman',
  },
  {
    id: 'skf',
    title: 'SKF',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_a47e48a627.webp`,
    link: '/projects/skf',
  },
  {
    id: 'dhool',
    title: 'Dhool',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/dhool_thumbnail_5690679941.webp`,
    link: '/projects/dhool',
  },
  {
    id: 'canara',
    title: 'Canara Bank',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/canara_bank_thumbnail_362985374b.webp`,
    link: '/projects/canara',
  },
  {
    id: 'levisxappeal',
    title: 'Levis X Appeal',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_444726ca4a.webp`,
    link: '/projects/levisxappeal',
  },
  {
    id: 'vbl',
    title: 'VBL',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_6eead439f0.webp`,
    link: '/projects/vbl',
  },
  {
    id: 'swiggy',
    title: 'Swiggy',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_d02630f5a9.webp`,
    link: '/projects/swiggy',
  },
  {
    id: 'sap25',
    title: 'SAP 25 years',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_4b81e69ba1.webp`,
    link: '/projects/sap',
  },
  {
    id: 'pepsicokosi',
    title: 'PepsiCo kosi film',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_eb8035cb0a.webp`,
    link: '/projects/pepsicoKosi',
  },
  {
    id: 'lam',
    title: 'LAM Event',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_04b98c32de.webp`,
    link: '/projects/lam',
  },
  {
    id: 'docmydoc',
    title: 'Doc MY Doc',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_24ab31bb5c.webp`,
    link: '/projects/docmydoc',
  },
  {
    id: 'terralite',
    title: 'Teralite',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/thumbnail_c9f0bca141.webp`,
    link: '/projects/terralite',
  },
  {
    id: 'shopperstop',
    title: 'Shoppers Stop',
    description: 'Short description line.',
    imageUrl: `${API_BASE_URL}/uploads/shoppers_stop_thumbnail_3bdc1e5688.webp`,
    link: '/projects/shopperstop',
  },
];

export const relatedProjects: RelatedProject[] = [
  {
    imageUrl: `${API_BASE_URL}/uploads/Thumbnail_Akamai_e98ec23a74.webp`,
    title: 'Akamai',
    description: 'Fusing personality and authenticity',
    link: '/projects/akamai',
  },
  {
    imageUrl: `${API_BASE_URL}/uploads/BSF_Banner_8bb1b6c31e.webp`,
    title: 'BSF',
    description: 'Reasserting leadership and expertise',
    link: '/projects/bsf',
  },
  {
    imageUrl: `${API_BASE_URL}/uploads/DRL_Thumbnail_8bd6627090.webp`,
    title: 'DRL Report',
    description: 'Treasuring story and symbolism',
    link: '/projects/drlreport',
  },
  {
    imageUrl: `${API_BASE_URL}/uploads/KDEM_thumbanail_f37f8768a9.webp`,
    title: 'KDEM Project',
    description: 'Revitalizing energy with design',
    link: '/projects/kdem',
  },
];

export const sections: Record<string, SectionBlock> = {
  gallery: {
    heading: 'Creating desire at every touch point.',
    description: 'We craft powerful stories and design experiences across the complete brand experience to build timeless brand value.',
    items: [
      {
        title: 'Munchatantra',
        description: 'Description A1',
        imageUrl: `${API_BASE_URL}/uploads/1_21_06531b12d4.webp`,
        link: '/projects/munchatantra',
      },
      {
        title: 'Seafund',
        description: 'Description A2',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_f961116ecc.webp`,
        link: '/projects/seafund',
      },
      {
        title: 'BSF',
        description: 'Description A3',
        imageUrl: `${API_BASE_URL}/uploads/1_09_1f75910d6b.webp`,
        link: '/projects/bsf',
      },
      {
        title: 'LendersMark',
        description: 'Description A4',
        imageUrl: `${API_BASE_URL}/uploads/1_05_95128ccf07.webp`,
        link: '/projects/lendersmark',
      },
      {
        title: 'Mera Terah Run',
        description: 'Description A5',
        imageUrl: `${API_BASE_URL}/uploads/1_19_27687419fe.webp`,
        link: '/projects/mtr',
      },
      {
        title: 'Dhool',
        description: 'Description A6',
        imageUrl: `${API_BASE_URL}/uploads/dhool_thumbnail_5690679941.webp`,
        link: '/projects/dhool',
      },
      {
        title: 'Kheemasutra',
        description: 'Description A7',
        imageUrl: `${API_BASE_URL}/uploads/kheemasutra_thumbnail_97210a02b8.webp`,
        link: '/projects/kheemasutra',
      },
      {
        title: 'Kachumbar',
        description: 'Description A8',
        imageUrl: `${API_BASE_URL}/uploads/kachumbar_thumbnail_41938995da.webp`,
        link: '/projects/kachumbar',
      },
      {
        title: 'Karnataka',
        description: 'Description A9',
        imageUrl: `${API_BASE_URL}/uploads/1_10_ec61f835b7.webp`,
        link: '/projects/karnataka',
      },
      {
        title: 'Mypreciousgens',
        description: 'Description A10',
        imageUrl: `${API_BASE_URL}/uploads/MPG_thumbnail_56571d1e5b.png`,
        link: '/projects/genes',
      },
    ],
  },
  creative: {
    heading: 'Delivering Creativity That Connects.',
    description: 'We design bold visual identities and packaging that create emotional resonance and brand loyalty through storytelling.',
    items: [
      {
        title: 'Akamai',
        description: 'Creative description line 1.',
        imageUrl: `${API_BASE_URL}/uploads/1_20_2425bb02bb.webp`,
        link: '/projects/akamai',
      },
      {
        title: 'Kosi',
        description: 'Creative description line 2.',
        imageUrl: `${API_BASE_URL}/uploads/1_11_75c2791aa1.webp`,
        link: '/projects/kosi',
      },
      {
        title: 'Munchatantra',
        description: 'Creative description line 1.',
        imageUrl: `${API_BASE_URL}/uploads/1_21_06531b12d4.webp`,
        link: '/projects/munchatantra',
      },
      {
        title: 'Decathalon',
        description: 'Creative description line 2.',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_4d89d5778d.webp`,
        link: '/projects/decathalon',
      },
      {
        title: 'Nauvata',
        description: 'Creative description line 1.',
        imageUrl: `${API_BASE_URL}/uploads/NAUVATA_67c5d4ab6a.webp`,
        link: '/projects/nauvata',
      },
      {
        title: 'VMWare',
        description: 'Creative description line 2.',
        imageUrl: `${API_BASE_URL}/uploads/VM_WARE_688b2e8047.webp`,
        link: '/projects/vmware',
      },
    ],
  },
  inspire: {
    heading: 'Inspiring change through creativity.',
    description: 'We bring innovative concepts to life through design, ensuring every touchpoint reflects purpose and personality.',
    items: [
      {
        title: 'DRL Report',
        description: 'Inspire description 1',
        imageUrl: `${API_BASE_URL}/uploads/1_16_4bf405e26d.webp`,
        link: '/projects/drlreport',
      },
      {
        title: 'Kyoorius',
        description: 'Inspire description 2',
        imageUrl: `${API_BASE_URL}/uploads/1_14_a5dc463609.webp`,
        link: '/projects/kyoorius',
      },
      {
        title: 'KDEM Report',
        description: 'Inspire description X',
        imageUrl: `${API_BASE_URL}/uploads/1_03_3009241765.webp`,
        link: '/projects/kdem',
      },
      {
        title: 'Shoppers Stop',
        description: 'Inspire description Y',
        imageUrl: `${API_BASE_URL}/uploads/shoppers_stop_thumbnail_3bdc1e5688.webp`,
        link: '/projects/shopperstop',
      },
    ],
  },
  vision: {
    heading: 'Visionary design that defines the future.',
    description: 'We shape brands through inspiring stories and imagery that forge emotional connections and cultural relevance.',
    items: [
      {
        title: 'Levis x appeal',
        description: 'Vision description 1',
        imageUrl: `${API_BASE_URL}/uploads/1_04_17aa32288c.webp`,
        link: '/projects/levis',
      },
      {
        title: 'SAP GCA',
        description: 'Vision description 2',
        imageUrl: `${API_BASE_URL}/uploads/1_07_98455b3c77.webp`,
        link: '/projects/sapgca',
      },
      {
        title: 'SN Cures',
        description: 'Vision description X',
        imageUrl: `${API_BASE_URL}/uploads/1_18_4a00253dab.webp`,
        link: '/projects/sn',
      },
      {
        title: 'Revolutionari',
        description: 'Vision description Y',
        imageUrl: `${API_BASE_URL}/uploads/1_12_aae9c075f7.webp`,
        link: '/projects/revolutionari',
      },
      {
        title: 'PepsiCo Assam',
        description: 'Vision description X',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_d56114a080.webp`,
        link: '/projects/pepsico',
      },
    ],
  },
  identity: {
    heading: 'Shaping brand identity with intent.',
    description: 'We build distinctive brand visuals and messages that consistently resonate across every channel and interaction.',
    items: [
      {
        title: 'Nandoos',
        description: 'Identity description 1',
        imageUrl: `${API_BASE_URL}/uploads/1_15_8ccd7d4d1c.webp`,
        link: '/projects/nandoos',
      },
      {
        title: 'Revolutionari',
        description: 'Identity description 2',
        imageUrl: `${API_BASE_URL}/uploads/1_12_aae9c075f7.webp`,
        link: '/projects/revolutionari',
      },
      {
        title: 'FMR',
        description: 'Identity description X',
        imageUrl: `${API_BASE_URL}/uploads/FMR_thumbnail_d2c0a7d11c.webp`,
        link: '/projects/fmr',
      },
      {
        title: 'Decathalon',
        description: 'Identity description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_4d89d5778d.webp`,
        link: '/projects/decathalon',
      },
    ],
  },
  essence: {
    heading: 'Capturing the essence of brand expression.',
    description: 'We translate strategy into visual narratives that stand out and stand for something, across every brand interaction.',
    items: [
      {
        title: 'Quaker-Bowl of growth',
        description: 'Essence description 1',
        imageUrl: `${API_BASE_URL}/uploads/1_01_d8cfbaf4fa.webp`,
        link: '/projects/quaker',
      },
      {
        title: 'Practo',
        description: 'Essence description 2',
        imageUrl: `${API_BASE_URL}/uploads/1_22_63db44728c.webp`,
        link: '/projects/practo',
      },
      {
        title: 'Canara Bank',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/canara_bank_thumbnail_362985374b.webp`,
        link: '/projects/canara',
      },
      {
        title: 'Dil se Naman',
        description: 'Essence description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_2d5138c5d9.webp`,
        link: '/projects/dilsenaman',
      },
      {
        title: 'VBL',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_6eead439f0.webp`,
        link: '/projects/vbl',
      },
      {
        title: 'Swiggy',
        description: 'Essence description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_d02630f5a9.webp`,
        link: '/projects/swiggy',
      },
      {
        title: 'SKF',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/tumbnail_ab280c23e1.webp`,
        link: '/projects/skf',
      },
      {
        title: 'SAP 25 years',
        description: 'Essence description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_4b81e69ba1.webp`,
        link: '/projects/sap',
      },
      {
        title: 'PepsiCo Assam',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_d56114a080.webp`,
        link: '/projects/pepsico',
      },
      {
        title: 'PepsiCo Kosi film',
        description: 'Essence description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_eb8035cb0a.webp`,
        link: '/projects/pepsicoKosi',
      },
      {
        title: 'LAM Event',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_04b98c32de.webp`,
        link: '/projects/lam',
      },
      {
        title: 'Doc My Doc',
        description: 'Essence description Y',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_24ab31bb5c.webp`,
        link: '/projects/docmydoc',
      },
      {
        title: 'Levi\'s X Appeal',
        description: 'Essence description X',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_444726ca4a.webp`,
        link: '/projects/levisxappeal',
      },
    ],
  },
  product: {
    heading: 'Shaping brand identity with intent.',
    description: 'We build distinctive brand visuals and messages that consistently resonate across every channel and interaction.',
    items: [
      {
        title: 'Booket',
        description: 'Product description 1',
        imageUrl: `${API_BASE_URL}/uploads/1_02_fa51d2f7b6.webp`,
        link: '/projects/booket',
      },
      {
        title: 'Teralite',
        description: 'Product description 2',
        imageUrl: `${API_BASE_URL}/uploads/thumbnail_c9f0bca141.webp`,
        link: '/projects/terralite',
      },
      {
        title: 'Munchatantra',
        description: 'Product description X',
        imageUrl: `${API_BASE_URL}/uploads/1_21_06531b12d4.webp`,
        link: '/projects/munchatantra',
      },
    ],
  },
  canvas: {
    heading: 'Designing the canvas of iconic brands.',
    description: 'We transform ideas into visually compelling experiences that are memorable and meaningful across every platform.',
    items: [
      {
        title: 'Canvas Title 1',
        description: 'Canvas description 1',
        imageUrl: 'https://pearlfisher.wpenginepowered.com/wp-content/uploads/2023/11/BYOMA-Thumbnail.png',
        link: '#',
      },
      {
        title: 'Canvas Title 2',
        description: 'Canvas description 2',
        imageUrl: 'https://pearlfisher.wpenginepowered.com/wp-content/uploads/2023/11/Coppertone-Thumbnail.png',
        link: '#',
      },
      {
        title: 'Canvas Title A',
        description: 'Canvas description A',
        imageUrl: 'https://pearlfisher.wpenginepowered.com/wp-content/uploads/2023/11/Coppertone-Thumbnail.png',
        link: '#',
      },
      {
        title: 'Canvas Title B',
        description: 'Canvas description B',
        imageUrl: 'https://pearlfisher.wpenginepowered.com/wp-content/uploads/2023/11/Coppertone-Thumbnail.png',
        link: '#',
      },
    ],
  },
};

export const socialLinks: SocialLink[] = [
  {
    icon: 'fab fa-facebook-f',
    url: '#',
    label: 'Facebook',
  },
  {
    icon: 'fab fa-linkedin-in',
    url: '#',
    label: 'LinkedIn',
  },
  {
    icon: 'fab fa-instagram',
    url: '#',
    label: 'Instagram',
  },
  {
    icon: 'fab fa-youtube',
    url: '#',
    label: 'YouTube',
  },
  {
    icon: 'fab fa-twitter',
    url: '#',
    label: 'Twitter',
  },
];

export const sectionMap: Record<string, string[]> = {
  'All-projects': ['portfolio-section'],
  'Brand-identity': ['gallery-block'],
  'Environmental-graphic': ['creative-block'],
  'Book-design': ['inspire-block'],
  'Event-design': ['vision-block'],
  'Campaigns': ['identity-block'],
  'Film-Motion-Graphics': ['essence-block'],
  'Product': ['product-block'],
}; 